name: .NET CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: restore

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build the project
      run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Run tests
      run: dotnet test --verbosity normal --configuration Release
